### ISSUE TITLE
Missing regex.h on Windows

### ISSUE THREAD

**Issue by tingyuw** [JacquesCarette/Drasil#2316]
I got this problem (haskell-hvr/regex-posix#4) when I was trying to build the current version of Drasil.
Not sure why it's popping up now since it works fine before.

### Steps to reproduce: 
1.  Run `cabal install regex-posix -f _regex-posix-clib` in terminal
2. Add the following to the code/stack.yaml
```
extra-deps:
   - regex-posix-clib-2.7

flags:
   regex-posix:
      _regex-posix-clib: true
```
